### ISSUE TITLE
Vytvoření základního GUI aplikace

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#1]
Je třeba, aby prvky rozhraní měly už po vytvoření nějaké **"inteligentní" názvy**. Zpříjemní to práci programátorů, kteří pak nebudou nuceni přepisovat zdrojové kódy. 

Nezapomínat vkládat použité **obrázky do složky Images a "aktualizovat" resource soubor**.
Obrázky bych ukládal **v jednotném formátu**, třeba png, a jednotném dpi (třeba 72).
Zkus, jestli Qt podporuje vektorové obrázky - svg, apod. To by bylo hodně slušný.

Prostě si s tím vyhraj a hlavně commituj ať z toho taky něco máme! ;-)

**Comment by jstas** [comment]
V projektu jsou připraveny všechny obrázky, které jsou potřeba, "resource soubor" využit. Základní grafické rozhraní je víceméně připraveno, mám v plánu se pokusit využít ještě google fonty pro drobné vylepšení. Dále budu testovat vhodný widget pro zobrazování výstupu aplikace.
