### ISSUE TITLE
Blíží se konec FFT a MFCC?

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#11]
Milý @fkopriva,
nahrál jsem commit [Vytvření globálního konfiguračního souboru](https://github.com/fpartl/PocketEar/commit/a3d973d692a62ae375db5968df9a19bcba1d52e0), ve kterém jsem do konstruktoru Tvé třídy MFCCPerformer přidal tebou žádané parametry. Jenom bych se zastavil nad parametrem `overlapSubCount`, který říká kolik vzorků každého okénka nebude překryto s dalším okénkem, tj. když uvažujeme okénko dlouhé 1024 vzorků a překryv bude 25 %, tak hodnota toho parametru bude 768. Na tobě teď je, abys v konstruktoru s těmito novými proměnnými naložil podle svých představ. 

Ještě jsem Ti chtěl říct, že program mou úpravou skutečně začal padat, ale až ve chvíli, kdy se snažíš aplikaci vypnout (nedořešil jsem vypínání nového vlákna). Čili tato skutečnost Ti nijak nebrání ve vývoji třídy MFCC performer. A pokud program v této třídě padá, bude podle mého názoru opravdu chyba v ní - mohu se samozřejmě mýlit. 

Hodně zdaru při programování. Do pátku čekám, že mi MFCC budou lítat do ServerConnection.

**Comment by fkopriva** [comment]
Metoda pro kopírování dat ze zvukové karty do pole a následně vytvořený překryv je hotov. Metoda je navržena podle přání doktora Ekšteina, je využita kruhová fronta, a kissFFT už je také hotové, krásně vypisuje kladná čísla. Problém byl v tom, že komplexní číslo může mít zápornou reálnou i komplexní část čísla, tudíž se musí spočíst Euklidovská norma, abychom věděli délku vektoru, která nám řekne kladnou reálnou část. Jediný problém je ve volání knihovny Mfcc, kde funkce chce pole doublů, přičemž máme pole floatů. Když jsem zkoušel přepsat funkci na float, tak stejně vyhazuje chybu. I po konzultaci s doktorem Ekšteinem nevím v čem je chyba.

**Comment by fpartl** [comment]
Ahoj @fkopriva,
chybu s MFCC jsem ti opravil. Trochu mě zaráží, že MFCC jsou některé záporné, ale já o tom nic nevím. V posledním commitu máš zakomentovaný výpis těch MFCC. Akorát si zase přepiš cestu na svojí plochu. Chtělo by to udělat ty testy. Až to bude otestované, tak bych tě chtěl ještě jednou požádat, abys mi udělal kopii toho pole s mfcc. Normálně malloc a memcopy... V tom signálu bys mi potom předával tu kopii. O její uvolnění se už postarám já.
