### ISSUE TITLE
Vizualizace stavu serveru v hlavním okně

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#13]
Vážený kolego @jstas,
rád bych tě poprosil, jestli bys do hlavního okna aplikace, tj. MainWindow, nedal někam obrázek, který by ukazoval stav připojení. Stačí křížek nebo fajfka, v pozadí nějaký náznak serveru. Víš co myslím. Napiš mi sem potom názvy těch obrázků, který budou na výběr. Já si to tam potom napíšu do nějaký obslužný funkce. Díky moc, užij si pobyt u manželky a papa!

**Comment by jstas** [comment]
Zdravím z pobytu! 
Zvolil jsem trošku jiné řešení, než jsi naznačil, nicméně je možné, že by mohlo být vyhovující a postačující. Prázdný nekoulinkulovalinkatější label "pouze" zbarvený buď do červena (**red**) - **nepřipojeno**, nebo do "našeho" modra (**#1e90ff**) - **připojeno**. Obsluha je potřeba tedy pouze v podobě změny 'background-color' u elementu **State** v **mainwindow**.
Pic!

**Comment by fpartl** [comment]
Dopsal jsem funkcionality. Smazal jsem ten chybový výpis a nechal tam jenom čistě tu tečku. Vypadá to velmi slibně. Díky
