### ISSUE TITLE
Vyhledání několika vhodných knihoven pro MFCC

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#2]
Je třeba najít **několik knihoven** pro získání **MFCC** ze zvukového záznamu. Nutností je, aby se do této knihovny vkládala data **z mikrofonu zařízení**. Což znamená, že je třeba umět v Qt pracovat s mikrofonem.
Je toho dost a je to dost neurčité téma, ale věřím, že programátor tvého kalibru se s tím popasuje. 

Hlavně ty knihovny připrav **do úterý**, abychom je mohli ukázat doktoru Ekšteinovi. Ten nám snad poradí, co s&nbsp;tím dál.

Hlavní jsou commity, ať se někam hnem. 👍

**Comment by fkopriva** [comment]
Knihovny by byly - 

1. Kaldi
2. Aquila
3. PocketSphinx
4. SPTK
5. OpenSMILE

všechny jsou podporované. Ze Stackoverflow mi byla ještě doporučena FFTW. Myslím, že na tom, kterou implementujeme, se domluvíme s doktorem Ekšteinem. K implementaci záznamu zvuku, existuje třída QAudioRecorder přímo v prostředí Qt. Je trochu složitá, ale s tím se určitě poperu.

**Comment by fkopriva** [comment]
Po domluvě s doktorem Ekšteinem jsme se dohodli, že využijeme knihovnu Libmfcc. Po vysvětlení základů analýzy signálu, jsme pochopili, co musíme udělat s nahraným signálem. Takže musíme využít ještě knihovnu FFT. Taktéž nám bylo doporučeno, abychom si našli nějaký funkční open source program, který jsme také našli a využijem algoritmus z něho. Závěrem konzultace nám doktor Ekštein ještě poradil 2 aplikace, které fungují na podobném, možná i stejném principu, abychom mohli prozkoumat kód a vymyslet řešení. V příkladech v Qt creatoru, jsme našli velice podobnou aplikaci, její kód jsme prozkoumali. Zbývá už jen zjistit jak funguje tvorbu framů pomocí QAudioBufferu, který si je vytváří sám.
