### ISSUE TITLE
Doplnění algoritmu plnění polí pro FFT pomocí QAudioBufferů + drobnosti

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#3]
Milý Filípku,
nahrál jsem commit "Vytvoření třídy Recorder". V kódu máš napsány komentáře o tom, co je třeba dodělat. Není toho moc:

   1) Dopsat tělo metody, která se spouští při stisknutí tlačítka RecordButton. Domluv se  s @jstas jestli tam dal nějaký obrázek zastavení, abychom je mohli přepínat.
   2) Dopsat program co bude dynamicky plnit pole, která budeme předávat k FFT. Je to podobrobně popsáno komentářem v metodě processBuffer. V místě kde se bude volat FFT dej příslušný komentář.

Hodně štěstí a ať to lítá,
Fanda

**Comment by fkopriva** [comment]
Metoda pro RecordButton je napsaná + getter, který zjištuje stav. Změna obrázku je zajištěna. Viz commit  4024d7f.

**Comment by fkopriva** [comment]
Metoda pro plnění bufferů je vyřešena a napsána. Zítra musíme s doktorem Ekšteinem zkonzulovat jestli je memcpy vhodná funkce. Po domluvě kdyžtak upravím řešení. Viz commit c2d618a .
