### ISSUE TITLE
Vytvoření okna s nastavením aplikace (připojení k serveru)

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#4]
Je potřeba vytvořit okno pro nastavení IP adresy a portu vzdáleného serveru. Dále ještě nějaký check box pro volbu šifrovaného nebo nešifrovaného spojení. Na to je ještě třeba se zeptat doktora Moučka, protože si vůbec nejsem jistý, že by to říkal. Hlavní je jednotlivé komponenty pojmenovat už na čisto. Já tam pak napíšu kontroly správnosti a emitování signálů pro serverové vlákno.

**Comment by jstas** [comment]
Hotovo, okno připraveno, hodlám ještě drobně upravit vzhled, nicméně komponenty jsou pojmenovány tak, jak je třeba a nebrání nám nic je již nyní využít. To vše sdíleno v commitu 'Úprava "nastavení" aplikace.'
