### ISSUE TITLE
Dokončení překrývání polí v implementaci QAudioInput

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#6]
Milý Filipe,
v commitu "Tak to zase nahrává..." jsem do metody _MFCCPerformer::writeData_ zkopíroval kód z předchozího řešení. Je třeba to dotáhnout do stejné fáze jako byla před týdnem. Nezapomeň na inicializaci merge polí a práci s proměnnou _buffersProcessed_. Na to jsem tam taky zkopíroval metody od minule, ale je třeba to dát dohromady. Dal jsem si tam jenom nějak výpis pro ladění a vypadá to dobře. Když uděláš ty překryvy, tak to můžeš použít na zkontrolování jestli se to fakt překrývá ve správném místě. Až to budeš mít funkční, tak ten debug výpis smaž.

**Comment by fkopriva** [comment]
Překrývání by mělo být vyřešené, ještě tedy do příštího commitu připíšu překryv pro více než 2 pole a zakomentuju to pro doktora Ekšteina.

**Comment by fpartl** [comment]
Zkusil jsem to @fkopriva, ale neběhá to jak bych si představoval, totiž vůbec...

**Comment by fpartl** [comment]
Bohužel se zatím nepodařilo toto issue vyřešit. Problematika zde řešená byla přesunuta do issue #11.
