### ISSUE TITLE
Doladění vzhledu okna s nastavením

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#7]
Ahoj Jane,
v commitu "Odstranění možnosti šifrování kanálu" jsem nedbale odstranil zaškrtávací políčko z okna nastavení. Layout to nějak nepobral a nadělal slušnou paseku. Koukni na to.

**Comment by jstas** [comment]
Okénko z důvodu mé neschopnosti nalezení potřebné možnosti zarovnání by se vždy mělo zobrazit v levém horním rohu displaye zařízení, ovšem jinak je vše (předpokládám), jak má být.

**Comment by fpartl** [comment]
Výborně @jstas, jak všichni dobře víme, doktor Ekštein na vzhledu příliš nedbá a funkcionalita je na prvním místě. S radostí uzavírám toto issue.
