### ISSUE TITLE
Můžem vypisovat!

### ISSUE THREAD

**Issue by fpartl** [fpartl/PocketEar#8]
Milý @jstas,
máš tam připravené vlákno Sesil. Každé dvě sekunkdy emituje signály s přišlou zprávou. Ty jsem ti propojil se slotem MainWindow::showNewResponse. Tam se teda všechno bude dít - vyndat z baneru, přidat do seznamu, dát do baneru. Nezapomeň, tanhle slot se volá každé dvě sekundy.

**Comment by jstas** [comment]
Drazí borci, píšu to sem, desktop aplikace Githubu se zbláznila. Doufám, že je tam ten commit.
Zprovoznil jsem výpis zpráv na obrazovku. Teď mi zbývá podívat se na nějakej styl, neboť (:D) jsem nebyl schopnej ty "utíkající" zprávy ani zarovnat na střed. Poslední věc, kterou jsem si uvědomil až po rvačce s Githubem, nezměnil jsem název toho "textBrowseru," takže to je taky třeba ještě změnit.
